// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHO6pfPXdqHy9Zy_vikOqZBk9Xc4VZ7as',
    appId: '1:550798260716:web:5514d6bc13154de19f28c9',
    messagingSenderId: '550798260716',
    projectId: 'torkey-e14ec',
    authDomain: 'torkey-e14ec.firebaseapp.com',
    storageBucket: 'torkey-e14ec.appspot.com',
    measurementId: 'G-V44589PHGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWnsY5GJuEta4wvCqLN0n07iR9UH4HdCs',
    appId: '1:550798260716:android:af19646c6f687e7b9f28c9',
    messagingSenderId: '550798260716',
    projectId: 'torkey-e14ec',
    storageBucket: 'torkey-e14ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCZW4hdAZwWc9brUUAEtYGGgVIkgoiehQ',
    appId: '1:550798260716:ios:75f134b7625c06cc9f28c9',
    messagingSenderId: '550798260716',
    projectId: 'torkey-e14ec',
    storageBucket: 'torkey-e14ec.appspot.com',
    iosClientId: '550798260716-grvg0ucbt39hguqp9nv3or7lpunotub3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCZW4hdAZwWc9brUUAEtYGGgVIkgoiehQ',
    appId: '1:550798260716:ios:75f134b7625c06cc9f28c9',
    messagingSenderId: '550798260716',
    projectId: 'torkey-e14ec',
    storageBucket: 'torkey-e14ec.appspot.com',
    iosClientId: '550798260716-grvg0ucbt39hguqp9nv3or7lpunotub3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFirebase',
  );
}
